### ISSUE TITLE
Handling the Matrix<1,1> case

### ISSUE THREAD

**Issue by zibrov-zlobin** [tomstewart89/BasicLinearAlgebra#20]
Hi @tomstewart89,
writing a generic MxN Kalman filter using your library I've encountered a problem with handling the cases when an MxN matrix is multiplied by added to a 1x1 Matrix.

do you have any pointers on how to implement fix or work around?
thanks!

**Comment by tomstewart89** [comment]
Hi @zibrov-zlobin, 

That's awesome! A Kalman filter is one of the use cases I had in mind when I first wrote this library.

Regarding your problem, I seem to recall adding a method to cast a 1x1 matrix into its ElementType. Turns out that was a bad idea so I've since removed in the 2.3 release, can you make sure you're on this version? 

Failing that, could you just attach some minimal example code to illustrate the problem?

Thanks!

**Comment by zibrov-zlobin** [comment]
I am using version 2.3.0.
example code:
```c++
  BLA::Matrix<2, 2> A = {1, 1, 0, 1};
  BLA::Matrix<1, 1> x = {1};
  BLA::Matrix<2, 2> res;
  Multiply(A, x, res);
```

thanks!

**Comment by zibrov-zlobin** [comment]
upd: I think I've tracked down an error in my code that resulted in a situation like the posted above, which at a second thought is somewhat artificial and should not appear.

**Comment by tomstewart89** [comment]
Ok I see the problem. Basically `Multiply` does matrix multiplication so it expects the number of columns of `A` to match the number of rows of `x`. You might also be familiar with numpy which includes a feature called broadcasting which would do an elementwise multiplication of `x` on every element on `A`, but unfortunately this library doesn't support that (PRs are welcome though).

In the meantime if you'd like to do an elementwise multiplication on a `BLA::Matrix` you can just multiply it by an object of type `ElementType`. For example the following should work:

```
BLA::Matrix<2, 2> A = {1, 1, 0, 1};
BLA::Matrix<1, 1> x = {1};
BLA::Matrix<2, 2> res = A * x(0);
```

Hope that helps, I'll close this issue but if there's anything else feel free to reopen it.
