### ISSUE TITLE
problem on Invert matrix<1, 1>

### ISSUE THREAD

**Issue by YuriSizuku** [tomstewart89/BasicLinearAlgebra#66]
Here is the example. 

``` C

BLA::Matrix<1, 3> H; 
BLA::Matrix<3, 3> P; 
auto C = BLA::Invert(H*P*(~H));
```

And error occurs 
no instance of overloaded function "BLA::Invert" matches the argument list
argument types are: (BLA::Matrix<1, 1, float>)

It will be nice to implement this trivial situation.

**Comment by tomstewart89** [comment]
Hey @YuriSizuku , thanks for your feedback!

The problem is that the `Invert` function modifies the input matrix in-place so it expects an lvalue reference whereas the result of the operation `H*P*(~H)` is an rvalue. lvalues / rvalues are a bit tricky, you can read about them [here](https://en.cppreference.com/w/cpp/language/reference) if you're not already familiar with them.

You can fix this problem by setting the result of `H*P*(~H)` to a variable like so:
```
auto C = H*P*(~H);
BLA::Invert(C);
```
Or by using the `Inverse` function instead:
```
auto C = BLA::Inverse(H*P*(~H));
```
Hope that helps!

**Comment by YuriSizuku** [comment]
Thank you very much. 
Now I understand the difference  of `Invert` and `Inverse`.
I followed this example [HowToUse.ino](https://github.com/tomstewart89/BasicLinearAlgebra/blob/782afcee029544fe5b1dc25265ab8169ab2d0db4/examples/HowToUse/HowToUse.ino#L77). 
I think it will be very helpful to add some documents or comments to show the difference of this two function.
