### ISSUE TITLE
Not compatible with Streaming library

### ISSUE THREAD

**Issue by twrackers** [tomstewart89/BasicLinearAlgebra#74]
This compiles:
Serial << <matrix object> << "\n";

unless your sketch #include's <Streaming.h> to permit another line to:
Serial << <int variable> << endl;

The BLA definition of '<<' clashes with that in Streaming.  Had to replace second line with:
Serial.println(<int variable>);

which is annoying.

**Comment by insalt-glitch** [comment]
The way Arduino **intends** you to implement printing for your own data structure is like this:
```C
#include <Printable.h>

const long BAUD = 115200;

struct MyCustomDatastructure : public Printable
{
  float member;
  size_t printTo(Print& p) const { return p.print(member); }
};

void setup()
{
  Serial.begin(BAUD);
  MyCustomDatastructure structure;
  Serial.print(structure);
}

void loop() {}
```
However, this would break some of the current library features and most of the examples, since they use the streaming printing mechanism that is implemented here currently. The solution would be to implement something like this and one of these options:
- Remove the current streaming implementation of this library
- Use the current streaming implementation only if the `ARDUINO_STREAMING` macro is not defined. This would signal that the current sketch is not using the streaming library.
- Leave the current implementation and the two libraries remain incompatible.

Personally, I would argue that the second solution is the best, since this would likely not break the backwards compatibility (or at least require minimal changes). In the end, the decision is up to @twrackers since he maintains this project. I could submit a PR for this but will wait for a decision.

**Comment by tomstewart89** [comment]
Thanks for the input @insalt-glitch ! I'm happy to drop the streaming operators here and embrace `Printable` instead. The API breakage is unfortunate but those operators aren't a core part of the library. If you'd like to make a PR, I'd welcome it, otherwise I can take a look at some point when I have some time
